### ISSUE TITLE
if last test is successful all tests considered successful

### ISSUE THREAD

**Issue by sassbalint** [dlt-rilmta/emdummy#1]
There is some problem in the for loop of `make test` with exit status checking.
This is the potential cause.

**Comment by dlazesz** [comment]
This is indeed a bug. Good find! ;) 
What do you think the expected behaviour would be?
Exit on first failed test OR run all tests and fail if any of them were failed?

I have implemented a quick and dirty fix which do the latter.
But maybe the former version would be a more clear solution.

**Comment by dlazesz** [comment]
Fixed by #3
